### ISSUE TITLE
Make it possible to see more then one week in the graph.

### ISSUE THREAD

**Issue by xdjinnx** [AlbericoD/twitch-extension-analyze#1]
I want to be able to see more then one week in the graph.
Ideally I want to be able to select how many days I want to see.

It would also be nice if the graph goes left to right instead of right to left.

**Comment by AlbericoD** [comment]
cool, choosing the range of days that are already being made, there must also be a way to go to an entire page of the chart, about the direction of the chart you believe should have a button that changes the direction of the chart, so everyone likes , what do you think?

**Comment by xdjinnx** [comment]
I have never seen a chart go right to left before, but if you prefer that people can choose that, go a head! 👍

**Comment by AlbericoD** [comment]
Commit  https://github.com/AlbericoD/twitch-extension-analyze/commit/4877776263c463487c2bc7393055bbc2d8895c99 Fixed problem with order of graph presentation (is now: left to right)

**Comment by AlbericoD** [comment]
@xdjinnx I deployed the feature to select date in the chart, if you can check if it was what you envisioned, please let me know to close this question 

Commit ef7a46fd7dc36661a305fd84e4e44b3fa7944636 added date range to change chart view
Deploy 151c0189d362eb18442416ef6bf88c1e17f01052 

![Captura de tela de 2019-03-31 13-36-56](https://user-images.githubusercontent.com/25888798/55291876-5d8c2980-53ba-11e9-916e-b51a0c4b463c.png)

**Comment by xdjinnx** [comment]
Looking sharp!
