### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by AdamBD** [AlbericoD/twitch-extension-analyze#15]
Ran NPM install followed by NPM start after a clean clone:

			TypeScript error: Type '(record: IChannels) => Element' is not assignable to type '(text: unknown, record: {}, index: number) => ReactNode'.
			  Types of parameters 'record' and 'text' are incompatible.
			    Type 'unknown' is not assignable to type 'IChannels'.  TS2322
			
			    44 |         title='Live'
			    45 |         key='action'
			  > 46 |         render={(record: IChannels) => (
			       |         ^
			    47 |           <span>
			    48 |             <a href={`https://www.twitch.tv/${record.username}`} target='__blank'>
			    49 |               <Icon component={newTabLink} />

**Comment by AlbericoD** [comment]
Hello, thank you for reporting this problem, I looked into it and it looks like it's a bug in the dependency of UI called antd, there are some ways to solve this, the first would be to write to the TS compiler ignore this check in that line, it would look like this:

```jsx
//twitch-extension-analyze/src/components/table-channel.tsx  
<Column
        title='Live'
        key='action'
        //@ts-ignore
        render={(record: IChannels) => (
          <span>
            <a href={`https://www.twitch.tv/${record.username}`} target='__blank'>
              <Icon component={newTabLink} />
            </a>
          </span>
        )}
      />
``` 

Of course this is not the ideal solution would be just a palliative solution so as not to disturb the beginning of the project, there is a pull that sets this in the antd library that will correct this:
https://github.com/ant-design/ant-design/pull/17249

There is also an online version for you to analyze your CSV that can be found here: https://albericod.github.io/twitch-extension-analyze/#/
